### ISSUE TITLE
Pressing escape to close a modal does not allow you to reopen it.

### ISSUE THREAD

**Issue by Wicloz** [mozfet/meteor-autoform-materialize-modals#2]
To reproduce:
- Create a modal on a page
- Press the button to open the modal
- Press 'escape' on the keyboard

Expected behavior:
- Modal closes and can be opened again

Actual behavior:
- Modal closes but cannot be opened again

Notes:
- Clicking the cancel button to close the modal does allow you to open it again

**Comment by mozfet** [comment]
I will look into it tomorrow

**Comment by mozfet** [comment]
I have reproduced the issue and will probably have it fixed by tomorrow. The same error behaviour is true for clicking on the submit button.

**Comment by mozfet** [comment]
The difference between cancel and submit is that with cancel it is clear you are done with the modal. On clicking the submit button, this is not so simple, becuase AutoForm will first validate, and only submit when validation succeeds. However based on the form type, the behaviour can be anything from a regular HTTP post submit, or a insert or update on the collection if Collection2 is used, or an processed using on success event hook. Some forms are dynamically rendered and some are static. Some should remain on the DOM after submitted, others should be removed...

Where should the modal be closed then? In my own implementations, I clean up modals submits using autoform success events. How can this be improved?

**Comment by mozfet** [comment]
I suppose I can add a hook to each modal form to automatically close on success based on a template argument for the modal launcher...

Edit: there is already such a hook in modal.js... 
```
//add on success hook to form
    AutoForm.addHooks([instance.data.id], {
      onSuccess: function (formType, result) {
        console.log('closing', instance.modalId);
        instance.$('#'+instance.modalId).modal('close');
        $('.modal-overlay').remove();
      }
    });
```

I noticed a few issues with the hook though:
1) The modal is assumed to be inside the template, which is not true when modalParentId is not inside the template, which is often the case since modals often do not behave well inline with other content.
2) The modal div is not removed on success, it is only closed... reopening a closed modal probably does not work because it tries to re-init an modal that is already existing and creates another div.

To fix this I am closing the modal using the global jquery dom selector, and removing the modal div from the DOM on success. This means that modals forms are always created from scratch and always destoyed on submit, thus cannot be reused. This results in this hook:
```
//add on success hook to form
    AutoForm.addHooks([instance.data.id], {
      onSuccess: function (formType, result) {
        console.log('closing', instance.modalId);
        $('#'+instance.modalId).modal('close');
        $('#'+instance.modalId).remove();
        $('.modal-overlay').remove();
      }
    });
```

**Comment by mozfet** [comment]
I've fixed this in v1.0.5 and republished on Atmosphere.

**Comment by mozfet** [comment]
Also improved the modal example in playground v3.0.1.

**Comment by Wicloz** [comment]
After upgrading to 1.0.5 I can indeed reopen modals after submitting them. Unfortunately I still can't reopen modals after pressing escape to cancel them.

**Comment by mozfet** [comment]
Hmmmm.... I am not handling any keypress events atm only click events... must be MaterializeCSS or Autoform doing something... I'm working through MaterializeCSS docs, but cannot find any reference to what the behaviour of ESC should be... 

Perhaps I can intercept the keypress and handle it the same as cancel and prevent the event from propagating to wherever it is going now...

**Comment by Wicloz** [comment]
That would be nice

**Comment by mozfet** [comment]
Pffff.... turns out Meteor keyboard events are only triggered for form input types and we want it to trigger wherever... Found a [solution](https://stackoverflow.com/questions/27972873/meteor-keydown-keyup-events-outside-input), however for some reason when escape was pressed the bloody modal-overlay keeps hanging about. Materializecss has always had problems with these overlays... anyhoo... it works now, but the kaveat is the modal-overlay will not work correctly when multiple modals are open at the same time...

I did not stop the escape event from propagating, it does not seem necessary.

in Template.autoformMaterializeModal.onCreated: 
```
$(document).on('keyup', (e) => {
    console.log('keyup', e);
    if(e.key === 'Escape') {
      instance.$('#'+instance.modalId).modal('close');
      //TODO make this configurable
      $('#'+instance.modalId).remove();
      $('.modal-overlay').remove();
    }
  });
```

in Template.autoformMaterializeModal.onDestroyed:
```
const instance = Template.instance();
  //TODO make this configurable
  $('#'+instance.modalId).remove();
  $(document).off('keyup');
  $('.modal-overlay').remove();
```

**Comment by mozfet** [comment]
Fixed in v1.0.6. Atmosphere package was updated.

**Comment by Wicloz** [comment]
It works, thanks.
Even so, there is more (it never ends).
Clicking next to the modal also seems to close it in such a way it can't be opened again.

**Comment by Wicloz** [comment]
Somewhat more important is that the console is getting spammed with keyup and other events.

**Comment by mozfet** [comment]
Fixed in v1.0.7 - No more logging. All forms of dismissing works now...OK... unless you can think of another type of dismissing :)

PS: Learnt that unfortunately Materialize-css modals ready and complete callback does not work as per the documentation... I also learned that when dealing with modals its best not to use the instance.$ jquery instance, but rather the global $ jquery instance... what a drag!

```
  //open the modal
  $(modalSelector).modal({
    dismissible: false,
    ready: function () {
      console.log('ready');
    },
    complete: function () {
      console.log('complete');
      //TODO make this configurable
      $(modalSelector).remove();
      $('.modal-overlay').remove();
    }
  });
```

**Comment by Wicloz** [comment]
Am I correct to assume that you disabled the ability to close modals by clicking next to them? Whilst not ideal it is an acceptable solution and at least allows the modals to work from a users perspective.

**Comment by mozfet** [comment]
Actually no, in the beginning I tried, but none of the modal parameters seems to want to work with the current version of materialize-css… so it still worked when I tested it… did it stop closing the modal for you when clicking outside?

**Comment by Wicloz** [comment]
For me on both Firefox and Chrome form modals no longer close after clicking outside of them.
I'm using materialize-css 0.100.2.

**Comment by mozfet** [comment]
I must have been sleeping... when I tested it now it did not work... anyway...

I commented out the modal init code completely.  I tested it with Meteor 1.5.2 with Autoform 6.0 and Materialize 0.100.2; it works in the playground on both  chrome and safari. 

This has now been confirmed fixed and fully tested in v1.0.8. Atmosphere has been updated.

**Comment by Wicloz** [comment]
All forms of dismissal work properly now.
The only problem my OCD is having is that the closing animations are different for all 4 types.

**Comment by mozfet** [comment]
I'll let your OCD deal with it then... or make a pull request :)
